<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

/**
 * This is the base-model class for table "resource".
 *
 * @property integer $id
 * @property string $fieldString
 * @property string $fieldNumber
 * @property string $fieldDate
 * @property string $comment
 *
 * @property \common\models\Subresource[] $subresources
 * @property string $aliasModel
 */
abstract class Resource extends \yii\db\ActiveRecord
{


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'resource';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['fieldString', 'fieldNumber', 'fieldDate'], 'required'],
            [['fieldNumber'], 'number'],
            [['fieldString', 'fieldDate', 'comment'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'fieldString' => 'Field String',
            'fieldNumber' => 'Field Number',
            'fieldDate' => 'Field Date',
            'comment' => 'Comment',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubresources()
    {
        return $this->hasMany(\common\models\Subresource::className(), ['resourceId' => 'id']);
    }


}
