<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

/**
 * This is the base-model class for table "subresource".
 *
 * @property integer $id
 * @property string $message
 * @property integer $resourceId
 *
 * @property \common\models\Resource $resource
 * @property string $aliasModel
 */
abstract class SubResource extends \yii\db\ActiveRecord
{


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'subresource';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['message', 'resourceId'], 'required'],
            [['resourceId'], 'integer'],
            [['message'], 'string', 'max' => 255],
            [
                ['resourceId'],
                'exist',
                'skipOnError' => true,
                'targetClass' => \common\models\Resource::className(),
                'targetAttribute' => ['resourceId' => 'id']
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'message' => 'Message',
            'resourceId' => 'Resource ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getResource()
    {
        return $this->hasOne(\common\models\Resource::className(), ['id' => 'resourceId']);
    }


}
